[package]
name = "hywoma"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
serde = { version = "1", features = ["derive"] }
bincode = "1"
serde_json = "1.0.149"
chrono = "0.4.43"
